listen = "0.0.0.0:8001"
pac_template = "template/pac.tmpl"

[proxy]

  [proxy.outer]
  address = "100.109.79.65:3128"
  target_file = "example/outer.csv"

  [proxy.internal]
  address = "100.74.93.123:3128"
  target_file = "example/internal.csv"

  [proxy.direct]
  target_file = "example/direct.csv"
